### ISSUE TITLE
ascent_macro: Upgrade syn to >= v2

### ISSUE THREAD

**Issue by langston-barrett** [s-arash/ascent#18] opened 2023-08-04 17:14 UTC
`syn` has undergone a major version bump. Since it's a slow package to compile, it'd be nice to have just one version of it in my dependency tree.

**Comment by s-arash** [comment] 2023-08-05 00:52
The problem is that currently [derive-syn-parse](https://github.com/sharnoff/derive-syn-parse), which I rely on for parsing, doesn't support `syn` v2. When a new version of `derive-syn-parse` is released with support for `syn` v2, I can switch to `syn` v2 as well.

I [raised an issue](https://github.com/sharnoff/derive-syn-parse/issues/7) there. Let's see what the author says in response.

**Closed** 2024-03-31 00:46 UTC
